[package]
name = "arbin-csv-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polars = { version = "0.23.1", features = ["lazy", "csv-file", "strings", "temporal", "cum_agg"]}
